# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: profiled_query.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import profile_pb2 as profile__pb2
import query_pb2 as query__pb2
import query_identifier_pb2 as query__identifier__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='profiled_query.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14profiled_query.proto\x1a\rprofile.proto\x1a\x0bquery.proto\x1a\x16query_identifier.proto\"e\n\rProfiledQuery\x12\"\n\x08query_id\x18\x01 \x01(\x0b\x32\x10.QueryIdentifier\x12\x15\n\x05query\x18\x02 \x01(\x0b\x32\x06.Query\x12\x19\n\x07profile\x18\x03 \x01(\x0b\x32\x08.Profileb\x06proto3')
  ,
  dependencies=[profile__pb2.DESCRIPTOR,query__pb2.DESCRIPTOR,query__identifier__pb2.DESCRIPTOR,])




_PROFILEDQUERY = _descriptor.Descriptor(
  name='ProfiledQuery',
  full_name='ProfiledQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query_id', full_name='ProfiledQuery.query_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='query', full_name='ProfiledQuery.query', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='profile', full_name='ProfiledQuery.profile', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=177,
)

_PROFILEDQUERY.fields_by_name['query_id'].message_type = query__identifier__pb2._QUERYIDENTIFIER
_PROFILEDQUERY.fields_by_name['query'].message_type = query__pb2._QUERY
_PROFILEDQUERY.fields_by_name['profile'].message_type = profile__pb2._PROFILE
DESCRIPTOR.message_types_by_name['ProfiledQuery'] = _PROFILEDQUERY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProfiledQuery = _reflection.GeneratedProtocolMessageType('ProfiledQuery', (_message.Message,), dict(
  DESCRIPTOR = _PROFILEDQUERY,
  __module__ = 'profiled_query_pb2'
  # @@protoc_insertion_point(class_scope:ProfiledQuery)
  ))
_sym_db.RegisterMessage(ProfiledQuery)


# @@protoc_insertion_point(module_scope)
